version: "3.8"

services:
  dante:
    image: debian:bookworm-slim
    container_name: dante-socks5
    restart: unless-stopped
    volumes:
      - ./danted.conf:/etc/danted.conf
    expose:
      - "1080"
    command: ["danted", "-f", "/etc/danted.conf", "-d", "1"]
    networks:
      - proxy-net

  stunnel:
    image: alpine:latest
    container_name: stunnel-tls
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./stunnel.conf:/etc/stunnel/stunnel.conf
      - ./certs:/etc/stunnel/certs
    command: ["stunnel", "/etc/stunnel/stunnel.conf"]
    depends_on:
      - dante
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
